//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProACC_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParallelType
    {
        public System.Guid ParallelId { get; set; }
        public Nullable<int> ParallelName { get; set; }
        public string Parallel_Name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_By { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
