//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProACC_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceAllocation
    {
        public System.Guid ResourceAllocation_Id { get; set; }
        public System.Guid Instance_Id { get; set; }
        public System.Guid Activity_ID { get; set; }
        public string User_ID { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Cre_on { get; set; }
        public System.Guid Cre_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ActivityMaster ActivityMaster { get; set; }
        public virtual Instance Instance { get; set; }
    }
}
